#!/bin/sh

: '
Convienience shell script to connect to a remote.it service specified by user
default host ip is the public ip of this computer

'


TOKEN="$RT3_TOKEN"
DEV_KEY="$RT3_DEVKEY"
DEVICE_ADDRESS=${1?Error: no device address given}
HOSTIP=${2:-$RT3_LAPTOP_PUBLIC_IP}

## get login credntials and store in json file
curl -X POST \
     -H "token:$TOKEN" \
     -H "developerkey:$DEV_KEY" \
     -d "{\"wait\":\"true\",\"deviceaddress\":\"$DEVICE_ADDRESS\", \
          \"hostip\":\"$HOSTIP\" }" \
     https://api.remot3.it/apv/v27/device/connect | jq '.' >> tmp.json


## obtain new server and port number from downloaded credentials
PRX_srv=$(jq -r '.connection | .proxyserver' tmp.json)
PRX_prt=$(jq -r '.connection | .proxyport' tmp.json)

## display new login info
echo "New Proxy server: $PRX_srv port: $PRX_prt"

## delete file to prevent build up of entries
rm tmp.json

## remove content of env vars
unset PRX_srv
unset PRX_prt
